Automatically Install Modules If Not Found
ThioJoe/YT-Spammer-Purge pull request #373
Opened 2022-01-11 19:23 UTC by TechStudent11

# Related Issue/Addition to code
Please delete options that are not relevant.

- Automatically Install Modules If Not Found

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Proposed Changes
- Automatically Install Modules If Not Found

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-01-11 19:33 UTC, Kurdakov commented
see https://www.pythonpool.com/pip-vs-pip3/ your assumption
if platform.system() == "Windows":
    pip_exe = "pip"
  else:
    pip_exe = "pip3"

that in Windows it's pip is incorrect.
pip3 though should always do the job, but then again, it does not look as a good practice - almost nobody uses automatic installation.

2022-01-11 20:00 UTC, compsup commented on YouTubeSpammerPurge.py
> +  os.system(f"{pip_exe} install -r requirements.txt")
Use `subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])`

2022-01-11 20:02 UTC, compsup requested changes
Use a try statement to attempt to install using pip3 first and if that fails try pip:

```
try:
 subprocess.call(['pip3', 'install', '-r requirements.txt'])
except:
 subprocess.call(['pip', 'install', '-r requirements.txt'])
```
I realize the issue if the OS has both pip and pip3 where pip is for python2 and pip3 is for python3, trying to find solutions

2022-01-11 21:45 UTC, Kurdakov commented
> Use a try statement to attempt to install using pip3 first and if that fails try pip:
> 
> ```
> try:
>   subprocess.check_call(['pip3', 'install', '-r requirements.txt'])
> except:
>   try:
>     subprocess.check_call(['pip', 'install', '-r requirements.txt'])
>   except:
>     pass
> ```

pip3 always works if python version 3 is installed (pip is just symlink to pip3 in this case), so in suggested snippet instead modules could be erroneously installed to python2 (if it is present and is default installation)

2022-01-11 21:52 UTC, compsup commented
> pip3 always works if python version 3 is installed (pip is just symlink to pip3 in this case), so in suggested snippet instead modules could be erroneously installed to python2 (if it is present and is default installation)

Except in linux installing using pip will only install python2 modules, unless im miss-reading what you said

2022-01-11 22:34 UTC, TechStudent11 commented
> > pip3 always works if python version 3 is installed (pip is just symlink to pip3 in this case), so in suggested snippet instead modules could be erroneously installed to python2 (if it is present and is default installation)
> 
> Yes thats correct, so only need to try pip3

got it.

2022-01-11 22:47 UTC, compsup approved these changes
Looks good

2022-01-12 13:41 UTC, TechStudent11 commented
Closing in favor of https://github.com/ThioJoe/YT-Spammer-Purge/discussions/213#discussioncomment-1949942

2022-01-13 22:35 UTC, TechStudent11 commented
Reopening just in case that get's merged.

2022-01-14 15:07 UTC, ThioJoe commented
I'd rather not have things auto install, especially because it could really mess up someone's virtual environments if they forget to load it

2022-01-14 15:07 UTC, closed without merging

2022-01-14 15:08 UTC, TechStudent11 commented
ok got it