Add benchmark and changes for rapidfuzz
ThioJoe/YT-Spammer-Purge pull request #752
Opened 2022-03-21 06:31 UTC by pusham7359

# Related Issue/Addition to code

- Changed calculating Levenshtein distance library from **python-Levenshtein** to **rapidfuzz**.
- This doesn't change the script's logic, it just makes it faster.
- Benchmark (For 10,000 pairs of randomly generated sentences with 10 to 1000 characters):
    - **python-Levenshtein**: 3.83 seconds
    - **rapidfuzz**: 0.12 seconds
- This time difference will be huge with a higher number of sentence pairs.
- **rapidfuzz** is a well-known and widely used library.
- I've added a benchmark file as well for you to compare the time for these libraries. If required I can remove this from PR and just keep the changes for **rapidfuzz**.

## Type of change

- [x] Optimization (non-breaking change which optimizes the code)

# Proposed Changes
- Use rapidfuzz instead of python-Levenshtein

# Additional Info
- Github repo for [rapidfuzz](https://github.com/maxbachmann/RapidFuzz/commit/c950f833d0589938ccf2884b9acb4a4f4e0ada91)

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2022-03-21 08:14 UTC, micziz approved these changes
LGTM! Really good performance. (ps, are you paid to say these things?)

2022-03-21 08:35 UTC, pusham7359 commented
Not at all, just an enthusiast. Checked this repo after Linus' video on this.

2022-03-21 16:02 UTC, EthanHindmarsh requested changes
Why include Scripts/benchmark_distance.py?
Other than that, LGTM✅

2022-03-21 17:30 UTC, pusham7359 commented on Scripts/benchmark_distance.py
> +from Levenshtein import ratio
Scripts/benchmark_distance.py is kept only to validate the performance difference by maintainers/contributors. I can remove the file as it does not add anything to the main logic. Please feel free to advise on this and I'll make changes accordingly.

2022-03-21 17:35 UTC, ThioJoe commented
Hmm i'll have to look at this

2022-03-24 20:00 UTC, TechStudent11 reviewed
If the scores are what they say on the tin, then I think this improvement will have a great impact.

2022-04-02 04:12 UTC, pusham7359 commented
@ThioJoe did you get a chance to look at this?

2022-04-02 18:25 UTC, ThioJoe commented
I'm holding off on this until I actually get to work on the next feature release 2.17, not sure exactly when I'll get to it

2022-04-10 18:06 UTC, merged

2022-04-11 07:29 UTC, DinhHuy2010 commented
tested

2022-04-11 09:57 UTC, Firecul commented
> tested

Is there a good difference in speed?

2022-04-11 14:57 UTC, TechStudent11 commented
> tested

Not really useful if you don't provide the results of the test.